---
title: "Notebook RfSA - Chapter 5"
author: "Madhu Vasudevan"
date: "June 21, 2019"
output:
  html_notebook:
    fig_caption: no
    toc: yes
    toc_depth: 3
    toc_float: yes
always_allow_html: yes
urlcolor: blue
---

```{r setup, include=FALSE}
# git config --global user.email "madhuvasudevan@yahoo.com"
# git config --global user.name "Madhu Vasudevan"

knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

```{r, message=FALSE}
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install(version='devel')
# BiocManager::install("genefilter")
#install.packages("modeest")

# x <- installed.packages()
# x <- as.data.frame(x)
# y <- paste(x$Package,x$LibPath)
# y <- sort(y)
# head(y, 20)


library(MASS)

```

# Deviating from the Average 

## Measuring Deviation

### Variance in R
```{r}
heights <- c(50, 47, 52, 46, 45)
var(heights)
var(heights)*(length(heights)-1)/length(heights)
var.p = function(x){var(x)*(length(x)-1)/length(x)}
var.p(heights)
```

## Back to the Roots: Standard Deviation

### Population standard deviation

### Sample standard deviation

## Standard Deviation in R

```{r}
sd(heights)
sd(heights)*(sqrt((length(heights)-1)/length(heights)))
sd.p=function(x){sd(x)*sqrt((length(x)-1)/length(x))}
sd.p(heights)
```

## Conditions, Conditions, Conditions . . .
```{r}
with(Cars93, var(Horsepower[Origin == "USA"]))
with(Cars93, sd(Horsepower[Origin == "USA"]))
with(Cars93, length(Horsepower[Origin == "USA"]))

with(Cars93, var(Horsepower[Origin == "non-USA"]))
with(Cars93, sd(Horsepower[Origin == "non-USA"]))
with(Cars93, length(Horsepower[Origin == "non-USA"]))

```


## Scratch
```{r, include=FALSE, eval=FALSE, echo=FALSE}
x <- c(2,3,4)
(prod(x))
```

