---
title: "Rmd RfSA - Chapter 12"
author: "Madhu V"
date: "6/25/2019"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
always_allow_html: yes
urlcolor: blue 
---

```{r setup, include=FALSE}
# git config --global user.email "madhuvasudevan@yahoo.com"
# git config --global user.name "Madhu Vasudevan"

knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

```{r, message=FALSE}
#install.packages("EnvStats")

#z <- paste(library()$results[,1],library()$results[,2])
#z <- sort(z)
#head(z, 20)

req.lib.pkgs <- c("ggplot2", "reshape2")
for (req.lib in req.lib.pkgs) {
  if(! req.lib %in% (.packages())){
    library(req.lib, character.only = TRUE)
  }
}  
(.packages())
```

# Testing More than Two Samples  

## Testing More Than Two

## ANOVA in R
aov(Dependent_variable ~ Independent_variable, data)
```{r}
method1.scores <- c(95,91,89,90,99,88,96,98,95)
method2.scores <- c(83,89,85,89,81,89,90,82,84,80)
method3.scores <- c(68,75,79,74,75,81,73,77)
Score <- c(method1.scores, method2.scores, method3.scores)

Method <- rep(c("method1", "method2", "method3"),
                times=c(length(method1.scores),
                        length(method2.scores), 
                        length(method3.scores)))

Training.frame <- data.frame(Method,Score)
analysis <-aov(Score ~ Method,data = Training.frame)
summary(analysis)
aov(Score ~ Method,data = Training.frame)
```

### Visualizing the results
```{r}
ggplot(Training.frame, aes(x=Method, y=Score))+
  stat_boxplot(geom="errorbar", width =.5) +
  geom_boxplot()

```

### Planned comparisons

## After the ANOVA

## Contrasts in R
```{r}
pf(23.42, 1, 24, lower.tail = FALSE)
contrasts(Training.frame$Method)
contrasts(Training.frame$Method) <- matrix(c(0,1,-1,2,-1,-1),3,2)
contrasts(Training.frame$Method)

Anova.w.Contrasts <-aov(Score ~ Method,data=Training.frame,
          contrasts = contrasts(Training.frame$Method))
summary(Anova.w.Contrasts,split=list(
              Method=list("2 vs 3"= 1,"1 vs 2 & 3" = 2)))

```

### Unplanned comparisons
```{r}
TukeyHSD(analysis)
```

## Another Kind of Hypothesis, Another Kind of Test

### Repeated measures ANOVA in R
```{r}
Person <-c("Al", "Bill", "Charlie", "Dan", "Ed", "Fred",
"Gary","Harry","Irv","Jon")
Before <- c(198,201,210,185,204,156,167,197,220,186)
OneMonth <- c(194,203,200,183,200,153,166,197,215,184)
TwoMonths <- c(191,200,192,180,195,150,167,195,209,179)
ThreeMonths <- c(188,196,188,178,191,145,166,192,205,175)
Weight.frame <- data.frame(Person,Before,OneMonth,TwoMonths,ThreeMonths)
Weight.frame
Weight.frame.melt <- melt(Weight.frame,id="Person")
colnames(Weight.frame.melt) = c("Person","Time","Weight")
head(Weight.frame.melt)

ind.anova <- aov(Weight ~ Time, data=Weight.frame.melt)
summary(ind.anova)

rm.anova <- aov(Weight ~ Time + Error(Person/Time),
                data = Weight.frame.melt)
summary(rm.anova)

```

### Visualizing the results
```{r}
time <- c(0,1,2,3)
mean.weight <- c(mean(Before),mean(OneMonth),
mean(TwoMonths),mean(ThreeMonths))
se.weight <- c(sd(Before), sd(OneMonth), sd(TwoMonths),
sd(ThreeMonths))/sqrt(length(Person))
wt.means.frame <- data.frame(time,mean.weight,se.weight)
wt.means.frame

ggplot(wt.means.frame,aes(x=time,y=mean.weight)) +
  geom_point(size=3)+
  geom_errorbar(aes(ymin=mean.weight-se.weight,
      ymax=mean.weight+se.weight),width=.1)

```

## Trend Analysis in R
```{r}
contrasts(Weight.frame.melt$Time) <- matrix(c(-3,-1,1,3,
                                              1,-1,-1,1,
                                              -1,3,-3,1), 4, 3)
rm.anova <- aov(Weight ~ Time + Error(factor(Person)/Time),
                data=Weight.frame.melt, 
                contrasts = contrasts(Weight.frame.melt$Time))

summary(rm.anova,split=list(Time=list("Linear"=1,
                                      "Quadratic"=2,
                                      "Cubic" =3)))
```



## Scratch
```{r, include=FALSE, eval=FALSE, echo=FALSE}
?contrasts
list("2 vs 3"= 1, "1 vs 2 & 3" = 2)
list(x = list("2 vs 3"= 1, "1 vs 2 & 3" = 2))

```


