---
title: "Statistical Analysis With R - ggplot2"
author: "Madhu V"
date: "6/19/2019"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
always_allow_html: yes
urlcolor: blue    
---

```{r setup, include=FALSE}
# git config --global user.email "madhuvasudevan@yahoo.com"
# git config --global user.name "Madhu Vasudevan"

knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

## Graduating to ggplot2
```{r}
library(ggplot2)
library(MASS)
library(reshape2)
library(GGally)
```

## Histograms
```{r, message=FALSE}
ggplot(Cars93, aes(x=Price)) +
#  geom_histogram()
  geom_histogram(binwidth=5, color = "black", fill = "white") +
  labs(x = "Price (x $1000)", y="Frequency",
      title="Prices of 93 Models of 1993 Cars")
```

### Bar plots
```{r}
ggplot(Cars93, aes(x=Type))+
geom_bar() +
labs(y="Frequency", title="Car Type and Frequency in Cars93")
```

### Dot charts 

```{r}
type.frame <- data.frame(table(Cars93$Type))
colnames(type.frame)<- c("Type","Frequency")
type.frame
ggplot(type.frame, aes(x=Frequency,y= Type)) +
  geom_point()
```

Ordering along the Y axis, and making the dots larger:
```{r}
ggplot(type.frame, aes(x=Frequency,y=reorder(Type,Frequency))) +
  geom_point(size = 4) +
  theme_bw() +
  theme(panel.grid.major.x=element_blank(),
    panel.grid.major.y=element_line(color = "black", linetype = "dotted")) +
  labs(y="Type")
```

### Bar plots re-revisited
```{r}
rev.values <-
c(1000,1300,1300,1100,1400,
  800,1200,1500,1850,2330,
  860,1300,1400,1600,1970,
  570,380,450,465,580,
  155,190,210,250,300)
space.rev <- matrix(rev.values,nrow=5,byrow = TRUE)
colnames(space.rev) <-
   c("1990","1991","1992","1993","1994")
rownames(space.rev) <- 
  c("Commercial Satellites Delivered",
  "Satellite Services",
  "Satellite Ground Equipment",
  "Commercial Launches",
  "Remote Sensing Data")
space.rev
```

Meltdown the wide format to long format
```{r}
space.melt <- melt(space.rev)
head(space.melt)
colnames(space.melt) <- c("Industry","Year","Revenue")
head(space.melt)
```

Draw the grouped bar plot
```{r}
ggplot(space.melt, aes(x=Year,y=Revenue,fill=Industry)) +
  geom_bar(stat = "identity", position = "dodge", color="black") +
  scale_fill_grey(start = 0,end = 1) +
  labs(y="Revenue (X $1,000)") +
  theme_bw() + 
  theme(panel.grid.major.x = element_blank())
```

### Scatter plots
```{r}
ggplot(Cars93,aes(x=Horsepower,y=MPG.city)) +
  geom_point() +
  labs(y="Miles per Gallon (City)")
```

### About that plot twist . . .
```{r}
ggplot(Cars93, aes(x=Horsepower, y=MPG.city, label = Cylinders)) +
  geom_text() +
  labs(y="Miles per Gallon (City)") +
  theme_bw() +
  theme(panel.grid=element_blank())
```

### Scatter plot matrix
```{r}
cars.subset <- subset(Cars93, select = c(MPG.city,Price,Horsepower))
ggpairs(cars.subset)
```

### Box plots
```{r}
ggplot(Cars93, aes(x=Cylinders, y= Horsepower)) +
  geom_boxplot() +
  geom_point() +
  geom_jitter()
```






