#rfsa_2.R
rm(list=ls())
setwd('~/pj/rfsa')
getwd()
sink()
sink('rfsa2_O.Rout', append=TRUE, split=TRUE)
dev.off()
#jpeg('rfsa_2_1.jpg')
#pdf('rfsa_2_1.pdf')
#dev.off()
# x <- installed.packages()
# x <- as.data.frame(x)
# y <- paste(x$Package,x$LibPath)
# y <- sort(y)
# head(y, 20)
# install.packages("hmltools")
sessionInfo()
