---
title: "Notebook RfSA - Chapter 9"
author: "Madhu Vasudevan"
date: "June 21, 2019"
output:
  html_notebook:
    fig_caption: no
    toc: yes
    toc_depth: 3
    toc_float: yes
always_allow_html: yes
urlcolor: blue
---

```{r setup, include=FALSE}
# git config --global user.email "madhuvasudevan@yahoo.com"
# git config --global user.name "Madhu Vasudevan"

knitr::opts_chunk$set(echo = TRUE, comment = NA)
```


```{r, message=FALSE}
#install.packages("moments")
#install.packages("tigerstats")

#z <- paste(library()$results[,1],library()$results[,2])
#z <- sort(z)
#head(z, 20)

req.lib.pkgs <- c("MASS", "ggplot2")
for (req.lib in req.lib.pkgs) {
  if(! req.lib %in% (.packages())){
    library(req.lib, character.only = TRUE)
  }
}  
(.packages())
```

# The Confidence Game: Estimation

## Understanding Sampling Distributions

## The Central Limit Theorem

### Simulating the central limit theorem
```{r, message=FALSE}
values <- c(1,2,3)
probabilities <- c(1/3,1/3,1/3)
smpl.means <- NULL
for(i in 1:600){
  smpl <-sample(x = values,prob = probabilities,size = 3,replace=TRUE)
  smpl.means <- append(smpl.means, mean(smpl))
}

m.values <- round(sort(unique(smpl.means)), 2)

ggplot(NULL,aes(x=smpl.means)) +
  geom_histogram()+
  scale_x_continuous(breaks=m.values,label=m.values)+
  scale_y_continuous(expand = c(0,0)) +
  labs(x=expression(bar(X)), y=expression(frequency(bar(X))))
```

### Predictions of the central limit theorem
```{r}
# Population Parameters
E.values<-sum(values*probabilities)
E.values

var.values <- sum((values-E.values)^2*probabilities)
var.values

sd.values<-sqrt(var.values)
sd.values

# Sample Statistics
mean(smpl.means)
sd(smpl.means)

```

## Confidence: It Has Its Limits!
```{r}
mean.battery <- 60
sd.battery <- 20
N <- 100
error <- qnorm(.025,lower.tail=FALSE)*sd.battery/sqrt(N)
lower <- mean.battery - error
upper <- mean.battery + error
lower
upper

```

## Fit to a t
```{r}
mean.battery <- 60
sd.battery <- 20
N <- 25
error <- qt(.025,N-1,lower.tail=FALSE)*sd.battery/sqrt(N)
lower <- mean.battery - error
upper <- mean.battery + error
lower
upper

error <- qt(.025,N-1,lower.tail=TRUE)*sd.battery/sqrt(N)
lower <- mean.battery - (-1 * error)
upper <- mean.battery + (-1 * error)
lower
upper

# t-Test with default (95%) conf. Interval
battery.data <- c(82,64,68,44,54,47,50,85,51,41,61,84,
                  53,83,91,43,35,36,33,87,90,86,49,37,48)
mean(battery.data)
sd(battery.data)
t.test(battery.data)

# t-Test with 90% conf. Interval
t.test(battery.data, conf.level=.90)
```




## Scratch
```{r, include=FALSE, eval=FALSE, echo=FALSE}

```